### PR TITLE
Members of the 60th Legislative Assembly of New Brunswick.

### PR DESCRIPTION
**Pull request by DrMeers**
Update to use https://www1.gnb.ca/legis/bios/60/index-e.asp

### CODE REVIEW

**Comment by jpmckinney** [comment]
Thanks!

**Comment by DrMeers** [comment]
Thank you @jpmckinney  :) How long does it take between merging a PR and seeing the data updated on http://represent.opennorth.ca/representatives/new-brunswick-legislature/ ?

**Comment by jpmckinney** [comment]
It should be about 24 hours. First it's scraped at http://scrapers.herokuapp.com and then imported into the API.

**Comment by DrMeers** [comment]
Great to know, thanks James!

**Pull request merged**
