### PR TITLE
Update PE

### PR DESCRIPTION
**Pull request by DrMeers**
See also https://github.com/opennorth/represent-canada-data/pull/36 and https://github.com/opencivicdata/ocd-division-ids/pull/248

### CODE REVIEW

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
Merged and deployed. Thanks!

**Comment by DrMeers** [comment]
Thank you @jpmckinney :)

**Comment by DrMeers** [comment]
@jpmckinney I can't figure out why the deployed changes haven't brought through the new reps... when I run it locally, I get Trish Altass et al -- but she doesn't exist on https://scrapers.herokuapp.com/represent/ca_pe/ . The scraper says its running successfully each day, but something isn't right?!

**Comment by jpmckinney** [comment]
I see Trish Altass there. The problem was that I hadn't updated the ID of the boundary set in the Django admin of represent.opennorth.ca. Altass is now returned by the API: http://represent.opennorth.ca/representatives/?last_name=Altass&format=apibrowser Thanks for reporting!

**Pull request merged**
