### PR TITLE
Update country-ca.csv -- 

### PR DESCRIPTION
**Pull request by DrMeers**
see https://github.com/opencivicdata/ocd-division-ids/pull/268 and https://github.com/opennorth/represent-canada-data/pull/38

### CODE REVIEW

**Comment by DrMeers** [comment]
@jpmckinney why would this scraper still be failing with `psycopg2.errors.ForeignKeyViolation: insert or update on table "opencivicdata_post" violates foreign key constraint "opencivicdata_post_division_id_82fef8df_fk_opencivic"
DETAIL:  Key (division_id)=(ocd-division/country:ca/province:ns/ed:53) is not present in table "opencivicdata_division".` according to https://scrapers.herokuapp.com/ ?

**Comment by jpmckinney** [comment]
Aha, the PostgreSQL database needs to be updated with the new divisions. I'll try to get to that but going on vacation soon.

**Comment by DrMeers** [comment]
Thank you @jpmckinney !

**Comment by jpmckinney** [comment]
You should get in touch with Open North's executive director, merlin@opennorth.ca, about whether I can provide access.

**Comment by DrMeers** [comment]
Thanks James, I've emailed. Is this something that you might still get to in the meanwhile?

**Comment by jpmckinney** [comment]
It's not looking good for me getting around to this.

**Comment by DrMeers** [comment]
Thanks for the update. I still haven't heard back from my email. Is it a long/complex process to update?

**Comment by jpmckinney** [comment]
Generally the simplest option is to reset Heroku's database, import the new IDs, then let the scrapers run. See the steps under "Setup the database" at https://github.com/opennorth/scrapers_ca_app

If you're happy to do that, then I think I still have access to add you as a collaborator on Heroku.

**Comment by DrMeers** [comment]
Ok thanks!

**Comment by DrMeers** [comment]
Any updates on this @jpmckinney ?

**Comment by jpmckinney** [comment]
What's your email address? You can reach me at jamespetermckinney at gmail.

**Comment by DrMeers** [comment]
Thanks @jpmckinney 

I completed the "steps under "Setup the database" at https://github.com/opennorth/scrapers_ca_app"

```
$  heroku pg:reset DATABASE -a scrapers
 ▸    WARNING: Destructive action
 ▸    postgresql-tapered-24149 will lose all of its data
 ▸    
 ▸    To proceed, type scrapers or re-run this command with
 ▸    --confirm scrapers
> scrapers
Resetting postgresql-tapered-24149... done
$ heroku run pupa dbinit ca -a scrapers
Running pupa dbinit ca on ⬢ scrapers... up, run.6029 (Hobby)
Operations to perform:
  Apply all migrations: contenttypes, core, elections, legislative, pupa
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying core.0001_initial... OK
  Applying core.0002_post_maximum_memberships... OK
  Applying core.0003_field_docs... OK
  Applying core.0004_auto_20171005_2028... OK
  Applying elections.0001_initial... OK
  Applying elections.0002_auto_20170731_2047... OK
  Applying elections.0003_election_fk... OK
  Applying elections.0004_field_docs... OK
  Applying elections.0005_auto_20170823_1648... OK
  Applying elections.0006_auto_20171005_2029... OK
  Applying elections.0007_auto_20171022_0234... OK
  Applying legislative.0001_initial... OK
  Applying legislative.0002_more_extras... OK
  Applying legislative.0003_time_changes... OK
  Applying legislative.0004_auto_20171005_2027... OK
  Applying legislative.0005_auto_20171005_2028... OK
  Applying pupa.0001_initial... OK
  Applying pupa.0002_auto_20150906_1458... OK
  Applying pupa.0003_auto_20151118_0408... OK
  Applying pupa.0004_identifier... OK
  Applying pupa.0005_auto_20170522_1935... OK
  Applying pupa.0006_identifier_jurisdiction... OK
10399 divisions found in the CSV, and 0 already in the DB
10399 divisions created
$ heroku run -a scrapers python manage.py migrate --noinput
Running python manage.py migrate --noinput on ⬢ scrapers... up, run.6888 (Hobby)
Operations to perform:
  Apply all migrations: auth, contenttypes, core, legislative, pupa, reports
Running migrations:
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying reports.0001_initial... OK
  Applying reports.0002_auto_20170224_0238... OK
```

However https://scrapers.herokuapp.com/ now appears to be blank -- did I miss a step?

**Comment by DrMeers** [comment]
Hmm, `update` seemed to work, but `upload` gives an error:

`botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.`

**Comment by jpmckinney** [comment]
Hmm, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are still set in the heroku config, so my only guess is that Open North deleted the related user or bucket (Open North had "cleaned up" AWS previously without knowing what they were doing – like deleting DNS).

**Comment by jpmckinney** [comment]
Anyway, upload just controls the downloads on this page, which are not frequently used: http://represent.opennorth.ca/data/

When I `curl -I http://represent.opennorth.ca.s3.amazonaws.com/csv/representatives/complete.csv` I see a Last-Modified of May 28, 2021, so I guess that's when the change was made. This is around the time that the new ED started and the remaining person who knew anything technical about Represent left, so that probably explains it.

**Pull request merged**
