### PR TITLE
Et 3857 fix ca mp

### PR DESCRIPTION
**Pull request by yi-yang-github**
Note that I have to run 

`PYTHONIOENCODING=utf8 pupa update ca`

as the python 3 default encoding seems to be not utf-8, and having some issues with French characters in the names.

At least in the docker env of this project, which is what I used.

### CODE REVIEW

**Comment by yi-yang-github** [comment]
actually db works too now. after I drop / re-init db a few times.

**Comment by jpmckinney** [comment]
Can you remove the commented-out `pprint` and the commented-out Adam Vaughan code?

**Comment by yi-yang-github** [comment]
Hi @jpmckinney / @mirabuck, the commented code lines are removed as requested.

**Comment by mirabuck** [comment]
This works for me locally.  Merging and deploying.

**Pull request merged**
