### PR TITLE
Sainte anne de bellevue scraper

### PR DESCRIPTION
**Pull request by iepmas**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Do `pip install pre-commit` and `pre-commit install`. Then, the first time, run `pre-commit run --all-files`.

It will tell you to remove the print statements.

**Comment by jpmckinney** [comment]
Then also run `pre-commit run --all-files` in your other failing PRs.

**Comment by jpmckinney** [comment]
Hi @seamuslee001 @bzhangjma - @iepmas has some open PRs that need to be fixed.

**Comment by seamuslee001** [comment]
@jpmckinney thanks James I'll follow up with Sam

**Comment by iepmas** [comment]
Updated python version in pre-commit.yaml. Pre-commit also removed a module from requirements.txt

**Pull request closed without merging**
