### PR TITLE
Add Scraper for Northwest Territories Legislative Assembly

### PR DESCRIPTION
**Pull request by seamuslee001**
This depends on https://github.com/opencivicdata/ocd-division-ids/pull/375

### CODE REVIEW

**Comment by jpmckinney** [comment]
Merged. I think you have permission to deploy?

**Comment by jpmckinney** [comment]
FYi, this gets:

```
Traceback (most recent call last):
  File "/app/reports/utils.py", line 71, in scrape_people
    report.report = subcommand.handle(args, other)
  File "/app/.heroku/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/app/.heroku/src/pupa/pupa/cli/commands/update.py", line 305, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/app/.heroku/src/pupa/pupa/cli/commands/update.py", line 173, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/app/.heroku/src/pupa/pupa/scrape/base.py", line 99, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/app/scrapers/ca_nt/people.py", line 68, in scrape
    handle_address(contact, "legislature")
  File "/app/scrapers/ca_nt/people.py", line 38, in handle_address
    + contact.xpath('./div[contains(@class, "office-address-wrapper")]/div[2]/div[2]')[0]
IndexError: list index out of range
```

**Comment by seamuslee001** [comment]
thanks @jpmckinney I'll look at that and I don't believe I have any permissions around deploy

**Comment by jpmckinney** [comment]
Can you send me your email address by some means? For me, you can click the envelope at https://www.open-contracting.org/about/team/#james-mckinney

**Pull request merged**
