### PR TITLE
Reenable Alberta Candidates scraper

### PR DESCRIPTION
**Pull request by rafe-murray**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Are we expecting an election soon?

**Comment by rafe-murray** [comment]
I doubt it. Most likely in 2027. I guess I wasn't really thinking about the use case for the data.

**Comment by jpmckinney** [comment]
I figure things could change again so we might as well leave these disabled.

**Comment by rafe-murray** [comment]
Ok that makes a lot of sense.

**Pull request closed without merging**
