### PR TITLE
Added division ids for moncton posts

### PR DESCRIPTION
**Pull request by patcon**
Tried testing the other PR against moncton, and realized this needed manual adding. If the style isn't how you like it, just say so, and I'll fix it. Also, if you *do* have a preferred style, perhaps we could codify that in an `.editorconfig` file, so other just get it for free?

### CODE REVIEW

**Comment by jpmckinney** [comment]
Please maintain the style that already exists in the code to make smaller diffs.

**Comment by patcon** [comment]
So first arg on same line?

**Comment by jpmckinney** [comment]
If you want to add an arg, just add it on the same line. So, for this file, I should see three edited lines. You don't need to edit the ranges. `+ 1` is not a bottleneck for performance.

**Comment by patcon** [comment]
ok, fixed and squashed. fyi there *was* a silly error before with one of the range starting at zero :/

**Comment by jpmckinney** [comment]
Why do you need to change the ranges? The outcome is the same before and after.

**Comment by jpmckinney** [comment]
Anyway, the point is to keep diffs small to make code review manageable. Style changes should be in their own PR, where nothing else changes.

**Comment by jpmckinney** [comment]
Also, to keep diffs small, please don't rename variables unless you are adding a lot more code than you are here.

The code base is extremely consistent at the moment. If you want to make style changes, they need to be done across the entire code base. Of course, that'd be a nightmare to review.

**Comment by patcon** [comment]
Sure. Just as the new person, didn't find the `i + 1` stuff clear, and thought it might help the next reader

**Comment by jpmckinney** [comment]
Sure, but if you want to change that, create a PR that does only that across all files.

**Comment by patcon** [comment]
:+1: Sorry for the noise

**Comment by jpmckinney** [comment]
Will you be adding `division_id` to all other `__init__` files? Also let me know if you're changing the ranges and variable names - seems sensible, but must be done project-wide.

**Comment by jpmckinney** [comment]
Btw, I'm currently in Korea if you see me make changes at odd hours.

**Comment by patcon** [comment]
I can make the changes elsewhere (will get me looking at the more general picture, which is good). Just scratching an itch with toronto committee scraping right now

**Comment by jpmckinney** [comment]
I've fixed all the ranges https://github.com/opencivicdata/scrapers-ca/commit/6945331d904cf5792326d7a13978e0ba4a1d5956

**Pull request merged**
