### PR TITLE
Toronto: Add ward metadata to post objects

### PR DESCRIPTION
**Pull request by patcon**
Re-ticketed from #128.

### CODE REVIEW

**Comment by jpmckinney** [comment]
So, the crazy `header_converter` is because Toronto is incorrectly putting "City of Toronto" in "District name" instead of the ward name, and is putting "Ward 1" etc. in "District ID" instead of just "1". So, for now, I'd prefer that you edit the CSV, since ideally they will have a conformant CSV that uses these columns properly. I'd reported all these errors and they're working on it.

**Comment by patcon** [comment]
Ok, I'll let you merge the other, then I'll rebase and fix that

**Comment by jpmckinney** [comment]
Merged #156

**Comment by patcon** [comment]
Question first: would it make more sense to just use "Ward X" instead of the "Blah (X)"? Looking around, it seems that in some place, we resolve post_id from role and label/district, and this would seem to be unnecessarily complicated if the ward name needs to be considered, no?

**Comment by jpmckinney** [comment]
If everything can be done based on the district ID (or a district name of "Ward X"), that'd probably make everything simpler.

**Comment by patcon** [comment]
Ok, if I'm understanding correctly, I think I've got it working as we'd like for now. (I didn't correct ward names in the CSV only because it wasn't necessary for this approach -- ward names come from district table and go in Post extras.

**Comment by patcon** [comment]
Rebased. Should be good for review/merge

**Comment by jpmckinney** [comment]
Remind me why we need this information under extras?

**Comment by jpmckinney** [comment]
Note to self: check that `organization.add_post` isn't doing anything that `yield post` doesn't accomplish.

**Comment by patcon** [comment]
I just feel it's better to have clean info on ward, not some label that mixes name and ward number :)

**Comment by jpmckinney** [comment]
Ah - on the other hand it introduces more code to maintain (and Toronto already has a special case Jurisdiction, which isn't ideal - I'm assuming you needed the identifier on council for a reason also). The division to which the post is associated already has the individual data elements (its `type_id` is the number, though the Division class doesn't make that an attribute).

**Comment by patcon** [comment]
I respectfully disagree.

The label is insufficient right now (ie. "Ward 38"), and is compound information even if "fixed" (ie. "Don Valley East (35)"). I feel it's entirely sensible to want just one piece of data without matching based on a formatting decision.

Sorry if that seems principled, but most everything else in this data set can be pull out and used directly to create UI layout, but that label is one of the few opinionated things. The PR makes for cleaner data imho

See: https://tocityhall-api.herokuapp.com/v0/posts

**Comment by jpmckinney** [comment]
Hmm, but those data elements should be properties of the division - not of the post. The imago API serializes the [division](https://github.com/opencivicdata/imago/blob/master/imago/serialize.py#L369) on the [post](https://github.com/opencivicdata/imago/blob/master/imago/serialize.py#L174) already. The preferred option would be for the Division to have an attribute for its `type_id` (which isn't always numeric, but it should have it as an attribute). That just requires changing [this line](https://github.com/opencivicdata/python-opencivicdata-divisions/blob/master/opencivicdata/divisions/__init__.py#L72). And then editing Imago (at the lines already cited) to expose that type ID. This way, it works for all jurisdictions, not just for Toronto. And it won't be jurisdictions-specific code throwing data under `extras` (which should be used very rarely).

**Comment by patcon** [comment]
Seems odd to have to add a concept of divisions to an app that otherwise doesn't require it, but I'll investigate adding it. I still think it fits as a property of the post, not the administrative division, but I'll drop it

**Comment by jpmckinney** [comment]
? Divisions appear throughout the app - the people scrapers fail if they can't reconcile to divisions, for example, which is a very important validation, as otherwise they can't be queried geographically.

Anyway, even in your data model, `number` is a property of `ward` which appears under `extras` on the Post. And "ward" is just a jurisdiction-specific term for "division". So, `number` is a property of Division even in the way you've modeled it.

**Comment by patcon** [comment]
Actually, can we convert this into a merge of the "catching of the yield" approach so that post objects are still amendable in a clear way (ie. not using `#add_post`)? I'd like to leave that as a template for how to add more data to the Post object (ie. start_date, end_date), when using the shared methods in utils.

**Comment by jpmckinney** [comment]
i.e. only keep the changes to `utils.py`? Sure. Using `add_post` just prevents dumping the Posts if the Organization doesn't validate, but there's no harm either way I think.

**Comment by patcon** [comment]
:+1: :)

**Pull request closed without merging**
