### PR TITLE
Toronto: Add agenda item type as subject

### PR DESCRIPTION
**Pull request by patcon**
http://app.toronto.ca/tmmis/viewPublishedReport.do?function=getAgendaReport&meetingId=10898

As seen in the link above, each agenda item has a type in its header. From what I've seen, there are a few options it can be:

* ACTION
* Information
* Presentation

### CODE REVIEW

**Comment by patcon** [comment]
Ah, sorry, meant to come and ask a question :)

So you think subjects straight-up, or would it be add to append something like `type:` so `type:ACTION`, `type:Information` etc. Or alternatively we could we abuse the `notes` array field (which is apparently usually for transcripts/minutes)?

Or does this all not matter, because we can just fix it later? I get the impression we wipe the database each time and create all-new uuid's, but I havent' dug in to check.

ALL THE QUESTIONS!

**Comment by jpmckinney** [comment]
Because Pupa is not very smart, and Represent doesn't need to preserve the UUIDs, we blow away people, memberships, posts and parties: https://github.com/opencivicdata/pupa/issues/65

If you want to keep those, it may be necessary to run a separate instance, as a lot of users depend on Represent.

**Comment by jpmckinney** [comment]
Here's the method that does the deleting: https://github.com/opennorth/scrapers_ca_app/blob/master/reports/utils.py#L40

**Comment by jpmckinney** [comment]
Hmm, yeah, this is not a bill subject. It'd be a bill classification maybe. Not sure why you'd prefix strings with `type:`.

**Comment by jpmckinney** [comment]
Reverted for now: https://github.com/opencivicdata/scrapers-ca/pull/169

**Comment by patcon** [comment]
I'm not sure about bill classification, as it's agenda item classification. Information and Presentation types won't be creating Bill objects, since no vote is held, if i undestand correctly. Or should we add agenda item classifications to the spec?

**Comment by jpmckinney** [comment]
Ah - I was looking too quickly. There is no field in the spec at the moment for this, but it'd be an agenda item classification I think.

**Comment by patcon** [comment]
And the idea of the prefix was because subject is the closest thing we had to something appropriate for agenda items, but would also be needed to agenda item categories (which Toronto happens to have internally in TMMS, although I have to talk to internal folks to figure out best way to get them out)

So `type:` prefix was just to keep it distinct from future *actual* subjects :)

**Comment by patcon** [comment]
And thanks, I'll look into adding something

**Comment by patcon** [comment]
For posterity, I below is the text of the email I sent to the City Clerk's Office

> Can you confirm what is the **difference between the "information" and "presentation"** classifications seen here:

> http://app.toronto.ca/tmmis/viewPublishedReport.do?function=getAgendaReport&meetingId=10898

> Also, would I be safe to assume that the **only types that will appear are**:

> * Information
> * Presentation
> * ACTION

> And lastly, am I correct that **only ACTION results in a vote taking place**?

I received the following reply from Matthew Green:

> Patrick,

> Thanks for your question.

> Generally, Action items are seeking some kind of direction or resolution from Council or Committee; usually there are proposed recommendations which Council or Committee can adopt or amend by vote.

> An Information Report is a City official's report that advises and informs without recommending.  A vote is required to dispose of the item (i.e., normally, a motion to receive the item).  The Council Procedure by-law outlines the procedures surrounding Information Reports and on a Motion to Receive For Information.  Section 27-143 is the rule specific to Information Reports at committee:

> http://www.toronto.ca/legdocs/municode/1184_027.pdf

> Similarly, an item marked Presentation is normally a verbal update, a ceremonial presentation or presentations to the committee without a covering report, such as slide presentations or playing of videos.  There would also be a vote to dispose of the item.  You'll see a lot of Presentation items at Economic Development Committee.  Here are the minutes from the last committee where you can see the committee's disposition on a number of presentation items:

> http://app.toronto.ca/tmmis/viewPublishedReport.do?function=getMinutesReport&meetingId=10971

> And it is correct that the only item classifications we have are Action, Information or Presentation.

> Matthew Green
 
> Council and Committee Administrator
 
> Legislative Information and Standards

> City Clerk's Office

**Comment by patcon** [comment]
So I was mistaken, and everything seems to get a vote, they're just never recorded in the vote record because no one ever bothers to request an individual tally :)

Still, these would be very useful to keep, as non-action agenda items are pretty boring, and likely not something we want to notify people on (for our city hall app)

**Pull request merged**
