### PR TITLE
Add Docker environment

### PR DESCRIPTION
**Pull request by djac**

### CODE REVIEW

**Comment by jpmckinney** [comment]
I prefer to have few (or no) shell scripts. Since `deploy.sh` is a one-time script, I think it's fine to inline in the readme as a list of commands. `shell.sh` is a single command, and I think it's better for users to become familiar with `docker-compose` than to rely on a magic command. Similarly, `db-refresh.sh` is only two commands, and is run very infrequently, so it's better to simply describe how to reset the DB in the readme with the two `docker-compose` commands.

Also, please modify the readme to use Markdown. Right now, it looks like bash snippets, and is not marked up for rendering on GitHub.

**Comment by djac** [comment]
@jpmckinney thanks for the feedback.

This PR should be ready to go now. Let me know if any other changes are needed.

**Comment by jpmckinney** [comment]
Likely easiest to start from the code in https://github.com/opencivicdata/scrapers-ca/blob/master/docker/README.md

The three manual steps are:

```
mkvirtualenv scrapers-ca --python=`which python3`
pip install -r requirements.txt
pupa dbinit ca
```

which are presently run by opening a Docker shell. Ideally this would be done by using `exec`.

**Comment by mirabuck** [comment]
@alberto56 I think that's actually expected behaviour.  That particular scraper was recently deleted.  You could try pupa update ca_on instead.  The full list of scraper names can be found as ca_ prefixed directories in the top level of the repo.

**Pull request merged**
